

  <div id="tabs">
  <ul>
    <li><a  href="#tabs-1">Cadastre seus produtos!</a></li>
    <li><a  href="#tabs-2">Faça suas listas de compra!</a></li>
    <li><a  href="#tabs-3">Conteúdo</a></li>
    <li><a  href="#tabs-4">Diferencial</a></li>
  </ul>

<section id="tabs-1">

    <p> <!-- Parágrafo -->
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque commodo tellus tortor, 
        faucibus sollicitudin urna auctor a. Class aptent taciti sociosqu ad litora torquent per 
        conubia nostra, per inceptos himenaeos. Maecenas consectetur urna volutpat velit posuere, 
        et molestie erat auctor. Curabitur ut lectus varius, placerat augue at, tincidunt nulla. 
        Vestibulum eu urna nibh. Pellentesque at velit tellus. Sed at sapien quis leo semper mollis 
        sed sollicitudin ipsum. Maecenas ante enim, venenatis ut mollis at, interdum vitae est. 
        Suspendisse imperdiet est in elit imperdiet, lobortis laoreet sem dignissim.
    </p>
</section>
<section id="tabs-2">
    <h3></h3>
    <p> 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque commodo tellus tortor, 
        faucibus sollicitudin urna auctor a. Class aptent taciti sociosqu ad litora torquent per 
        conubia nostra, per inceptos himenaeos. Maecenas consectetur urna volutpat velit posuere, 
        et molestie erat auctor. Curabitur ut lectus varius, placerat augue at, tincidunt nulla. 
        Vestibulum eu urna nibh. Pellentesque at velit tellus. Sed at sapien quis leo semper mollis 
        sed sollicitudin ipsum. Maecenas ante enim, venenatis ut mollis at, interdum vitae est. 
        Suspendisse imperdiet est in elit imperdiet, lobortis laoreet sem dignissim.
    </p>
</section>
<section id="tabs-3">
    <ul id="circle"> <!-- Segundo a w3c essa tag type é obsoleta -->
        <li>Salve suas compras!</li>
        <li>Imprima suas compras!</li>
        <li>Gere Estatísticas!</li>
        <li>Economize!</li>
    </ul>
</section>
<section id="tabs-4">
    <ol>
        <li>Rapidez</li>
        <li>Eficiência</li>
        <li>Segurança</li>
        <li>Dinâmico</li>
    </ol>

</section>
</div>
